<?php

namespace app\wx\controller;

use EasyWeChat\Foundation\Application;
use think\Controller;

class BaseController extends Controller
{
    //
    public function _initialize()
    {
        $app = new Application(config('wx'));
        $oauth = $app->oauth;

// 未登录
        if (!session('wechat_user')) {
            $url = strtolower("/" . \request()->module() . "/" . \request()->controller() . "/" . \request()->action());
            session('target_url', $url);
            //return $oauth->redirect();
            // 这里不一定是return，如果你的框架action不是返回内容的话你就得使用
            $oauth->redirect()->send();
//           halt(1);
        }

        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}
